WINDOW_TITLE = "MIDI Visualizer (MVP)"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60
BACKGROUND = "#000000"

DEFAULT_STYLE = "pulses"

PARTICLE_BASE_LIFETIME = 1.0
PARTICLE_MAX_LIFETIME = 1.8
PARTICLE_MIN_RADIUS = 8
PARTICLE_MAX_RADIUS = 48

MAX_PARTICLES = 2000
